### PR TITLE
Draft3 to Draft4 conversion: handle "any" type

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Fixes issue #1

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
Ping.
Could you please review this PR, it's very simple and straightforward.

**Comment by IvanGoncharov** [comment]
@geraintluff Can you please review this PR?

**Comment by IvanGoncharov** [comment]
@geraintluff This change is very important to me. Could please review it?

**Comment by geraintluff** [comment]
Hi - sorry, I wasn't getting notifications on this repo for some reason!

**Comment by IvanGoncharov** [comment]
@geraintluff Thanks.
Everything is merged so I close PR.

**Pull request closed without merging**
